kl_loss:
    pct_start: 0.0
    start_value: 1.0
    end_value: 1.0
    log_clip: 1.0e+3
    clip: 1.0e+9

parameter_prior_hparams:
  parameters: [0.4, 1.1]
  s_min: 0.01
  s_max: 1.5
  sample_parameter_per_batch: false