model: trade.BoltzmannGenerator

dataset:
  training_data_parameters: [600]
  name: ala2
  split: [0.8, 0.05, 0.15]

parameter_reference_value: 600.0

max_epochs: 60

flow_type: bgflow

flow_hparams:
  activation: silu
  architecture:
  - - TORSIONS
    - TORSIONS
    - true
  - - TORSIONS
    - TORSIONS
    - true
  - - TORSIONS
    - TORSIONS
    - true
  - - ANGLES
    - TORSIONS
    - true
  - - ANGLES
    - TORSIONS
    - true
  - - ANGLES
    - TORSIONS
    - true
  - - BONDS
    - REMAINING
    - true
  - - BONDS
    - REMAINING
    - true
  - - BONDS
    - REMAINING
    - true
  conditioner_type: residual
  constrain_chirality: false
  min_energy_structure_path: trade/bgflow_wrapper/data_ala2/position_min_energy.pt
  n_workers: 16
  spline_disable_identity_transform: true
  parameter_aware: true
  parameter_preprocessing: log
  temperature_steerable: false
  torsion_shifts: true
  use_sobol_prior: false

lr_scheduler: "onecyclelr"

batch_size: 289
optimizer:
  name: adam
  lr: 0.0001
  weight_decay: 3.7e-06

gradient_clip: 3.0

dequantization_noise: 0.0003
softflow: false

num_workers: 0
accelerator: "gpu"

nll_loss:
    pct_start: 0.0
    start_value: 1.0
    adaptive: false
    adaptive_weight: 1.0
    log_clip: 1.0e+3
    clip: 1.0e+9

trade_loss:
  adaptive: true
  adaptive_weight: 0.001
  alpha_adaptive_update: 0.0001031397281068186
  clip: 1000000000.0
  end_value: 0.2291192865618575
  log_clip: 1000.0
  pct_start: 0.3166782035278435
  start_value: 0.0
  additional_kwargs:  
    alpha_running_EX_A: 0.6455121371535668
    alpha_running_loss: 0.8
    average_importance_weights: true
    bs_expectation_computation: 5000
    check_consistency_with: ground_truth
    delta_huber: 0.0005
    epsilon_causality_weight: 0.1254057776582006
    evaluation_mode: beta_0_samples_gaussian_noise_parameter_scaling
    evaluation_stddev: 0.0003
    init_param_grid_in_log_space: true
    loss_mode: Huber
    mode: grid
    n_points_param_grid: 25
    n_samples_expectation_computation: 5000
    take_samples_from: flow
    update_freq_running_average_EX_A: 1000
    use_target_proposals: false

parameter_prior_hparams:
  parameters: [0.4, 1.1]
  s_min: 0.01
  s_max: 1.5
  sample_parameter_per_batch: true

plotting:
  interval: 5
  n_samples: 100000
  parameters: [300, 600, 1000]
  n_repeats_log_prob: 1
