model: trade.BoltzmannGenerator

dataset:
  training_data_parameters: [600]
  name: ala2
  split: [0.8, 0.05, 0.15]

parameter_reference_value: 600.0

max_epochs: 150

flow_type: freia

flow_hparams:
  n_transforms: 20
  prior: "normal"
  augmentation_dim: 60
  use_actnorm: true
  scale_latent_with_parameter: true
  coordinate_transform: constrained
  parameter_preprocessing: "log"
  coupling_hparams:
    coupling_type: "affine"
    hidden: [[128, 128, 128]]
    resnet: true
    parameter_aware: true
    activation: "silu"
    volume_preserving: false
    zero_init: true

lr_scheduler: "onecyclelr"

batch_size: 1024
optimizer:
  name: adam
  lr: 0.0003
  weight_decay: 1.0e-06

gradient_clip: 3.0

dequantization_noise: 0.0003
softflow: false

num_workers: 0
accelerator: "gpu"

nll_loss:
    pct_start: 0.0
    start_value: 1.0
    adaptive: false
    adaptive_weight: 1.0
    log_clip: 1.0e+3
    clip: 1.0e+9

trade_loss:
    pct_start: 0.4
    start_value: 0.0
    end_value: 0.1
    adaptive: true
    adaptive_weight: 1.e-3
    log_clip: 1.0e+3
    clip: 1.0e+9
    additional_kwargs:
      mode: continuous
      check_consistency_with: ground_truth
      take_samples_from: flow
      evaluation_mode: beta_0_samples_gaussian_noise_parameter_scaling
      evaluation_stddev: 0.0003


parameter_prior_hparams:
  parameters: [0.4, 1.1]
  s_min: 0.01
  s_max: 1.5
  sample_parameter_per_batch: true

plotting:
  interval: 5
  n_samples: 100000
  parameters: [300, 600, 1000]
  n_repeats_log_prob: 1
