trade_loss:
    pct_start: 0.2
    start_value: 0.0
    end_value: 1.0
    adaptive: false
    adaptive_weight: 1.e-3
    log_clip: 1.0e+3
    clip: 1.0e+9
    additional_kwargs:
      mode: grid
      check_consistency_with: ground_truth
      take_samples_from: flow
      epsilon_causality_weight: 0.9
      n_points_param_grid: 50
      alpha_running_EX_A: 0.5
      average_importance_weights: true
      update_freq_running_average_EX_A: 100
      alpha_running_loss: 0.5
      n_samples_expectation_computation: 5000
      bs_expectation_computation: 5000
      init_param_grid_in_log_space: true
      use_target_proposals: false
      evaluation_mode: beta_0_samples_gaussian_noise_parameter_scaling
      evaluation_stddev: 0.0003
      loss_mode: Huber
      delta_huber: 5.0e-4
