model: trade.BoltzmannGenerator

dataset:
  training_data_parameters: [1]
  name: multi_well_5d
  split: [0.8, 0.1, 0.1]

max_epochs: 20

flow_hparams:
  n_transforms: 15
  prior: "normal"
  augmentation_dim: 0
  use_actnorm: false
  scale_latent_with_parameter: true
  coordinate_transform: false
  parameter_preprocessing: "log"
  coupling_hparams:
    coupling_type: "rqspline"
    hidden: [256, 256]
    resnet: false
    parameter_aware: true
    activation: "silu"
    volume_preserving: false


lr_scheduler: "onecyclelr"

dequantization_noise: 0.0
softflow: false

batch_size: 512
optimizer:
  name: adam
  lr: 0.0002
  weight_decay: 0.0

gradient_clip: 3.0

num_workers: 0
accelerator: "gpu"

nll_loss:
    pct_start: 0.0
    start_value: 1.0
    end_value: 1.0
    log_clip: 1.0e+3
    clip: 1.0e+9

parameter_prior_hparams:
  parameters: [0.4, 1.1]
  s_min: 0.01
  s_max: 1.5
  sample_parameter_per_batch: true

plotting:
  interval: 3
  n_samples: 100000
  parameters: [0.5, 1]
  n_repeats_log_prob: 1

